server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:

  application:
    name: chatbot

profiles:
    active: test