server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    prefer-ip-address: true

spring:

  application:
    name: chatbot

  profiles:

    active: dev
